import about from './hedgehog.html'
import './css/hedgehog.css'
import './css/hedgehog-header.css'
import './css/hedgehog-banner.css'
import './css/hedgehog-footer.css'
import './css/hedgehog-about.css'
import './css/hedgehog-features.css'
import './css/hedgehog-enemies.css'
import './css/hedgehog-life.css'
import './css/hedgehog-chat.css'
import './css/hedgehog-register.css'
import '@fortawesome/fontawesome-free/js/all'
import './images/hedgehog-2.jpg'
import './images/hedgehog.jpg'
